packages:
  - packages/**
  - playground/**
  - "!**/test/**"
catalog:
  h3: ^1.15.4
  nitropack: ^2.12.4
  zod: ^4.0.14
  typescript: ^5.9.2
  tsup: ^8.5.0
  "@asteasolutions/zod-to-openapi": ^8.0.0
onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - nx
