packages:
  - packages/**
  - playground/**
  - '!**/test/**'
catalog:
  h3: ^1.15.1
  nitropack: ^2.11.1
  zod: ^3.24.2
  zod-openapi: ^4.2.3
  typescript: ^5.8.2
  tsup: ^8.3.6
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - nx
